parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     jobeet
    database_user:     root
    database_password: mYsEcret

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ffc06a611a745f3a1be610e021baab1cc70e0e93
